const del = require('del');
const gulp = require('gulp');
const concat = require('gulp-concat');
const uglify = require('gulp-uglify');
const autoprefixer = require('gulp-autoprefixer');
const htmlmin = require('gulp-htmlmin');
const cleanCSS = require('gulp-clean-css');
const imagemin = import('gulp-imagemin');
const gulpif = require('gulp-if');
const jeditor = require("gulp-json-editor");
const filter = require('gulp-filter');
const manifest = require('./src/manifest.json');
const zip = require('gulp-zip');

const paths = {
    src: './src/',
    dist: './dist/',
    build: './build/',
    cssDir: './src/assets/css/',
};

/**
 * Build process:
 * 1. Minify everything (js, css, html)
 * 2. Concat files
 * 3. Optimize images
 * 4. Replace things (path to files, etc.)
 * 5. Update manifest to match
 * 6. Remove unnecessary files (e.g. blocked.html)
 * 7. Zip files
 * 8. Push to Chrome, Firefox, Safari
 */

function buildString() {

}

function distFileName(browserName, ext) {
    return `dist-${browserName}${buildString()}.${ext}`;
}

gulp.task('cleanup', function () {
    return del(paths.dist);
});

function packJS(src, dist, concatName) {
    return gulp.src(
        Array.isArray(src)
            ? src.map((path) => paths.src + path)
            : paths.src + src
    )
        .pipe(gulpif(!!concatName, concat(concatName || '404')))
        .pipe(uglify())
        .pipe(gulp.dest(paths.dist + dist));
}

gulp.task('pack-js', async function () {
    packJS(
        [
            'scripts/events.js',
            'scripts/tabs.js',
            'scripts/utils.js',
            'scripts/alarm.js'
        ],
        '', 'background.js'
    );

    packJS(
        [
            "content.js",
            "scripts/utils.js",
            "scripts/timer.js",
            "scripts/screen-blocker.js"
        ],
        'scripts'
    );

    packJS('options/options.js', 'options');
    packJS('popup/popup.js', 'popup');
});

gulp.task('pack-css', function () {
    return gulp.src(paths.src + 'assets/css/*.css')
        .pipe(cleanCSS())
        .pipe(autoprefixer())
        .pipe(gulp.dest(paths.dist + 'assets/css'));
});

gulp.task('pack-html', function () {
    return gulp.src(paths.src + "**/*.html")
        .pipe(htmlmin({
            collapseWhitespace: true,
            includeAutoGeneratedTags: false,
            minifyCSS: true,
            minifyJS: true,
            minifyURLs: true,
            removeComments: true,
            removeEmptyAttributes: true,
            removeAttributeQuotes: true,
            removeRedundantAttributes: true,
            removeScriptTypeAttributes: true,
            removeStyleLinkTypeAttributes: true
        }))
        .pipe(gulp.dest(paths.dist));
});

gulp.task('optimize-images', async function () {
    const imageOptimizer = await imagemin;

    return gulp.src(paths.src + "/assets/images/*")
        .pipe(
            imageOptimizer.default([
                imageOptimizer.optipng({ optimizationLevel: 7 }),
                imageOptimizer.svgo()
            ])
        )
        .pipe(gulp.dest(paths.dist + "/assets/images"));
});

gulp.task('manifest-update', async function () {
    gulp.src(paths.src + 'manifest.json')
        .pipe(jeditor(function (json) {
            const i = json.content_scripts[0].js
                .findIndex((script) => script.includes("content.js"));
            json.content_scripts[0].js[i] = "/scripts/content.js";

            return json;
        }))
        .pipe(gulp.dest(paths.dist));
});

gulp.task('remove-unnecessary-files', async function () {
    return del(
        [
            'assets/blocked.html'
        ].map((path) => paths.dist + path)
    );
});

gulp.task('zip', async function (browserName) {
    gulp.src(paths.dist)
        .pipe(zip(distFileName(browserName, 'zip')))
        .pipe(gulp.dest(paths.build));
});

gulp.task('dist', gulp.series([
    'cleanup',
    gulp.parallel(['pack-js', 'pack-css', 'pack-html', 'optimize-images']),
    gulp.parallel([/**'replace'*/ 'manifest-update', 'remove-unnecessary-files']),
]));

gulp.task('push-update', gulp.series([
    'dist',
    'zip',
    // gulp.parallel([
    //     'chrome', 'firefox', 'safari',
    // ])
]));
